# Generated by Django 4.0.4 on 2022-04-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('shop', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
